# MyGICA v1.0 (TOML)

fps = '24000/1001'
#project_name = "千早不思议_sample.mp4"
project_suffix = '.mp4'
# 使用自动推测
#start = 1907
#end = 2098

# =====================================
# 源文件定义
# =====================================

[sources]
go1 = 'D:\qbitdownload\short\mygo\mygo1.mkv'
go2 = 'D:\qbitdownload\short\mygo\mygo2.mkv'
go3 = 'D:\qbitdownload\short\mygo\mygo3.mkv'
go4 = 'D:\qbitdownload\short\mygo\mygo4.mkv'
go5 = 'D:\qbitdownload\short\mygo\mygo5.mkv'
go6 = 'D:\qbitdownload\short\mygo\mygo6.mkv'
go7 = 'D:\qbitdownload\short\mygo\mygo7.mkv'
go8 = 'D:\qbitdownload\short\mygo\mygo8.mkv'
go9 = 'D:\qbitdownload\short\mygo\mygo9.mkv'
go10 = 'D:\qbitdownload\short\mygo\mygo10.mkv'
go11 = 'D:\qbitdownload\short\mygo\mygo11.mkv'
go12 = 'D:\qbitdownload\short\mygo\mygo12.mkv'
go13 = 'D:\qbitdownload\short\mygo\mygo13.mkv'

ji1 = 'D:\qbitdownload\short\mujica\mujica1.mkv'
ji2 = 'D:\qbitdownload\short\mujica\mujica2.mkv'
ji3 = 'D:\qbitdownload\short\mujica\mujica3.mkv'
ji4 = 'D:\qbitdownload\short\mujica\mujica4.mkv'
ji5 = 'D:\qbitdownload\short\mujica\mujica5.mkv'
ji6 = 'D:\qbitdownload\short\mujica\mujica6.mkv'
ji7 = 'D:\qbitdownload\short\mujica\mujica7.mkv'
ji8 = 'D:\qbitdownload\short\mujica\mujica8.mkv'
ji9 = 'D:\qbitdownload\short\mujica\mujica9.mkv'
ji10 = 'D:\qbitdownload\short\mujica\mujica10.mkv'
ji11 = 'D:\qbitdownload\short\mujica\mujica11.mkv'
ji12 = 'D:\qbitdownload\short\mujica\mujica12.mkv'
ji13 = 'D:\qbitdownload\short\mujica\mujica13.mkv'

black = 'cache_in\test_video_basic.mkv'
# 由 0_gen_black.py 生成的测试视频

bgm = 'D:\QQFile\2534666876\FileRecv\千早不思议_v1.wav'
# 找个音频替换上面这个，默认需要这个文件存在

#san-anon = 'D:\Pictures\圣爱音.png'
san-anon = '圣爱音.jpg'

# =====================================
# 应援色定义
# =====================================

[colors]
'灯' = '#77BBDD'
'爱音' = '#FF8899'
'乐奈' = '#77DD77'
'素世' = '#FFDD88'
'立希' = '#7777AA'
'MyGO!!!!!' = '#3388BB'

'初华' = '#BB9955'
'睦' = '#779977'
'海铃' = '#335566'
'若麦' = '#AA4477'
'祥子' = '#7799CC'
'Ave Mujica' = '#881144'

'tomori' = '#77BBDD'
'anon' = '#FF8899'
'rana' = '#77DD77'
'soyo' = '#FFDD88'
'taki' = '#7777AA'
'mygo' = '#3388BB'

'uika' = '#BB9955'
'mutsumi' = '#779977'
'umiri' = '#335566'
'nyamu' = '#AA4477'
'saki' = '#7799CC'
'mujica' = '#881144'

# =====================================
# 时间范围与字幕/动作定义
# =====================================

[[ranges]]
start = 1907
end = 2020
[[ranges.texts]]
text = "追随着行星引力在宇宙逃逸"
[[ranges.clips]]
source = "go1"
end = 29590

[[ranges]]
start = 2020
end = 2098
[[ranges.texts]]
text = "火爆脾气一脚踢到钛合金"
[[ranges.clips]]
source = "go1"
start = 29590
end = 29626
[[ranges.clips]]
source = "go1"
start = 30852
volume = -50
