# MyGICA v1.0 (TOML)
fps = '24000/1001'
#project_name = "千早不思议_sample.mp4"
project_suffix = '.mp4'
# 使用自动推测
#start = 1907
#end = 2098
# =====================================
# 源文件定义
# =====================================

[sources]
go1  = "E:/mygo/[SubsPlease] BanG Dream! It's MyGO!!!!! - 01 (1080p) [23181341].mkv"
go2  = "E:/mygo/[Ohys-Raws] Bang Dream! It`s MyGo!!!!! - 02 (BS4 1280x720 x264 AAC).mp4"
go3  = "E:/mygo/[Ohys-Raws] Bang Dream! It`s MyGo!!!!! - 03 (BS4 1280x720 x264 AAC).mp4"
go4  = "E:/mygo/[Ohys-Raws] Bang Dream! It`s MyGo!!!!! - 04 (AT-X 1280x720 x264 AAC).mp4"
go5  = "E:/mygo/[Ohys-Raws] Bang Dream! It`s MyGo!!!!! - 05 (AT-X 1280x720 x264 AAC).mp4"
go6  = "E:/mygo/[Ohys-Raws] Bang Dream! It`s MyGo!!!!! - 06 (AT-X 1280x720 x264 AAC).mp4"
go7  = "E:/mygo/[Ohys-Raws] Bang Dream! It`s MyGo!!!!! - 07 (AT-X 1280x720 x264 AAC).mp4"

go8  = "E:/mygo/[LPSub] BanG Dream! It's MyGO!!!!! [08][HEVC AAC][1080p][JPSC&JPTC].mkv"
go9  = "E:/mygo/[LPSub] BanG Dream! It's MyGO!!!!! [09][HEVC AAC][1080p][JPSC&JPTC].mkv"
go10 = "E:/mygo/[LPSub] BanG Dream! It's MyGO!!!!! [10][HEVC AAC][1080p][JPSC&JPTC].mkv"
go11 = "E:/mygo/[LPSub] BanG Dream! It's MyGO!!!!! [11][HEVC AAC][1080p][JPSC&JPTC].mkv"
go12 = "E:/mygo/[LPSub] BanG Dream! It's MyGO!!!!! [12][HEVC AAC][1080p][JPSC&JPTC].mkv"

go13 = "E:/mygo/[Ohys-Raws] Bang Dream! It`s MyGo!!!!! - 13 (AT-X 1280x720 x264 AAC).mp4"

ji1  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E01.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji2  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E02.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji3  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E03.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji4  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E04.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji5  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E05.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji6  = "E:/Mujica/[NanakoRaws] BanG Dream! Ave Mujica - 06 (AT-X 1920x1080 x265 AAC).mkv"
ji7  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E07.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji8  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E08.1080p.AMZN.WEB-DL.JPN.DDP2.0.H.264-ToonsHub.mkv"
ji9  = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E09.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji10 = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E10.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji11 = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E11.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji12 = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E12.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"
ji13 = "E:/Mujica/BanG.Dream!.Ave.Mujica.S01E13.1080p.UNEXT.WEB-DL.JPN.AAC2.0.H.264-ToonsHub.mkv"

black = 'cache_in\test_video_basic.mkv'
# 由 0_gen_black.py 生成的测试视频

bgm = 'E:\祥子的诱惑\千早不思议_v3.wav'
# 找个音频替换上面这个，默认需要这个文件存在

#san-anon = 'E:\MyGICA_withUI\圣爱音.jpg'
san-anon = '圣爱音.jpg'

# =====================================
# 应援色定义
# =====================================

[colors]
'灯' = '#77BBDD'
'爱音' = '#FF8899'
'乐奈' = '#77DD77'
'素世' = '#FFDD88'
'立希' = '#7777AA'
'MyGO!!!!!' = '#3388BB'

'初华' = '#BB9955'
'睦' = '#779977'
'海铃' = '#335566'
'若麦' = '#AA4477'
'祥子' = '#7799CC'
'Ave Mujica' = '#881144'

'tomori' = '#77BBDD'
'anon' = '#FF8899'
'rana' = '#77DD77'
'soyo' = '#FFDD88'
'taki' = '#7777AA'
'mygo' = '#3388BB'

'uika' = '#BB9955'
'mutsumi' = '#779977'
'umiri' = '#335566'
'nyamu' = '#AA4477'
'saki' = '#7799CC'
'mujica' = '#881144'

# =====================================
# 时间范围与字幕/动作定义
# =====================================

[[ranges]]
start = 1907
end = 2020
[[ranges.texts]]
text = "追随着行星引力在宇宙逃逸"
[[ranges.clips]]
source = "go1"
end = 29590

[[ranges]]
start = 2020
end = 2098
[[ranges.texts]]
text = "火爆脾气一脚踢到钛合金"
[[ranges.clips]]
source = "go1"
start = 29590
end = 29626
[[ranges.clips]]
source = "go1"
start = 30852
volume = -50
